baseURL: "https://blog.rogery.dev/"
languageCode: "zh"
title: "Roger Young"
theme: "paper-mod"


menu:
  main:
    # - name: Posts
    #   url: post
    #   weight: 1
    - name: Posts
      url: archives
      weight: 5
    - name: Search
      url: search/
      weight: 10
#    - name: Tags
#      url: tags/
#      weight: 10
#    - name: Categories
#      url: categories/
#      weight: 10
    - name: About
      url: about/
      weight: 0
        

markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true

Copyright: © 2022 [Roger Young](https://blog.rogery.dev/)

params:
  ShowCodeCopyButtons: true
  ShowToc: true
  ShowPostNavLinks: true
  ShowCopyRight: true
  gitRepo: https://github.com/rogeryoungh/blog
  profileMode:
    enabled: true
    title: "Roger Young" # optional default will be site title
    subtitle: "Welcome to my blog!"
    imageUrl: /avatar.png
    buttons:
    - name: All of my Posts
      url: "./archives"
  comments: true
  valine:
    enable: true
    appId: FIvl3vmw2mH3naQEJhErblHr-gzGzoHsz
    appKey: BhvzpBrJqPPzfK5phjDBiBb4
    avatar: 'mp'
    placeholder: '说点什么吧...'
    visitor: false
  socialIcons:
    - name: github
      url: "https://github.com/rogeryoungh"
    - name: telegram
      url: "https://t.me/rogeryoungh"
    - name: rss
      url: "index.xml"


outputs:
  home: ["HTML", "RSS", "JSON"]